apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maven-app
  name: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - image: IMAGE:BUILD_TAG
        name: maven-project
        imagePullPolicy: Always